openapi: 3.0.0
info:
  title: Movie Review API
  description:
    This API provides historical review and movie data of the movies.
    Raw data provided by  The Internet Movie Database(IMDb) and The Movie Database(TMDB).
  version: 1.0.0
servers:
  - url: /movie-api/v1
paths:
  /movie:
    get:
      summary: Returns a list of movies.
      tags:
        - movie
      operationId: controller.get_movies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MovieShort"
  /movie/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns complete details of the specified movie by id
      tags:
        - movie
      operationId: controller.get_movie_details_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Movie"
  /movie/latest/:
    get:
      summary: Returns list of new movies order by release date
      tags:
        - movie
      operationId: controller.get_movies_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieShort'
  /movie/casts:
    get:
      summary: Return list of movie star
      tags:
        - person
      operationId: controller.get_persons
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Person"
  /movie/cast/{cast_id}:
    parameters:
      - name: cast_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies that cast_id star in
      tags:
        - person
      operationId: controller.get_movies_cast
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieShort'
  /movie/companies:
    get:
      summary: Returns list of companies
      tags:
        - production company
      operationId: controller.get_companies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/ProductionCompany"
  /movie/company/{company_id}:
    parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies that company_id contribute in
      tags:
        - production company
      operationId: controller.get_movies_company
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieShort'
  /movie/genres:
    get:
      summary: Returns list of genres
      tags:
        - genre
      operationId: controller.get_genres
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Genre"
  /movie/genre/{genre_id}:
    parameters:
      - name: genre_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies with genre_id
      tags:
        - genre
      operationId: controller.get_movies_genre
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MovieShort"
  /movie/rating/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns movie's rating score from various of website
      tags:
        - rating
      operationId: controller.get_movie_rating
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Rating"
  /movie/AverageRating/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns average rating score from various of website
      tags:
        - rating
      operationId: controller.get_movie_average_rating_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AverageRating"
  /movie/AverageRating:
      get:
        summary: Returns average rating score from various of website
        tags:
          - rating
        operationId: controller.get_movie_average_rating
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: "#/components/schemas/AverageRating"
  /movie/AverageRating/limit/{limit}:
    parameters:
      - name: limit
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns average rating score from various of website
      tags:
        - rating
      operationId: controller.get_movie_average_rating_limit
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AverageRating"
  /movie/review/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns reviews from our primary data for specific movie
      tags:
        - review
      operationId: controller.get_movie_review
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Reviews"
  /movie/AverageReview:
    get:
      summary: Returns average review score from our primary data
      tags:
        - review
      operationId: controller.get_movies_average_review
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AverageReview"
  /movie/AverageReview/limit/{limit}:
    parameters:
      - name: limit
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns average review score from our primary data
      tags:
        - review
      operationId: controller.get_movies_average_review_limit
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/AverageReview"
          links:
            averageRating:
              operationId: controller.get_movies_average_rating_limit
              parameters:
                imdbId: $response.body#/imdbId
  /movie/AverageReview/{imbd_id}:
    parameters:
      - name: imbd_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns average review score of specific movie from our primary data
      tags:
        - review
      operationId: controller.get_movies_average_review_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/AverageReview"
  /movie/year/{year}:
    parameters:
      - name: year
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return list of movie release on specific year
      tags:
        - movie
      operationId: controller.get_movie_year
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/MovieShort"

components:
  schemas:
    MovieShort:
      type: object
      properties:
        id:
          type: integer
        imdb_id:
          type: string
        title:
          type: string
        release_date:
          type: string
        genre:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
    Movie:
      type: object
      properties:
        id:
          type: integer
        imdb_id:
          type: string
        title:
          type: string
        release_date:
          type: string
        cast:
          type: array
          items:
            $ref: "#/components/schemas/Person"
        genres:
          type: array
          items:
            $ref: "#/components/schemas/Genre"
        production_company:
          type: array
          items:
            $ref: "#/components/schemas/ProductionCompany"
    Genre:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    ProductionCompany:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Person:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    AverageRating:
      type: object
      properties:
        imdb_id:
          type: string
        title:
          type: string
        average_rating:
          type: number
    Rating:
      type: object
      properties:
        imdb_id:
          type: string
        title:
          type: string
        imdb:
          type: number
        metacritic:
          type: number
        tmdb:
          type: number
    AverageReview:
      type: object
      properties:
        imdb_id:
          type: string
        movie_name:
          type: string
        total_count:
          type: integer
        recommend:
          type: number
        avg_score:
          type: number
    Reviews:
      type: object
      properties:
        movie_name:
          type: string
        recommend:
          type: number
        score:
          type: number
        review:
          type: string
