openapi: 3.0.0
info:
  title: Movie Review API
  description:
    This API provides historical review and movie data of the movies.
    Raw data provided by  The Internet Movie Database(IMDb) and The Movie Database(TMDB).
  version: 1.0.0
servers:
- url: /movie-api/v1
paths:
  /movies:
      get:
        summary: Returns a list of movies.
        operationId: controller.get_movies
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/MovieShort'
  /movie/{movieId}:
      parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type : integer
      get:
        summary: Returns complete details of the specified movie by id
        operationId: controller.get_movies_details_id
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'
  /movies/latest/:
      get:
        summary: Returns list of new movies order by release date
        operationId: controller.get_movies_latest
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MovieShort'
  /movie/rating/{imdb_id}:
      parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type : integer
      get:
        summary: Returns movie's rating score from various of website
        operationId: controller.get_movies_rating
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Rating'
  /movies/AverageRating:
        get:
          summary: Returns average rating score from various of website for movies
          operationId: controller.get_movies_average_rating
          responses:
            200:
              description: Success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Rating'
  /movies/AverageReview:
        get:
          summary: Returns average review score from our primary data
          operationId: controller.get_movies_average_review
          responses:
            200:
              description: Success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Review'

components:
  schemas:
    MovieShort:
      type: object
      properties:
        id: 
          type: integer
        title: 
          type: string
        release_date:
          type: string
        genre:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
    Movie:
      type: object
      properties:
        title:
          type: string
        budget:
          type: number
        revenue:
          type: integer  
        release_date:
          type: string
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
        production_companies:
          type: array
          items:
            $ref: '#/components/schemas/ProductionCompany'
    Genre:
      type: object
      properties:
        name:
          type: string
    ProductionCompany:
      type: object
      properties:
        name:
          type: string
    Rating:
      type: object
      properties:
        id: 
          type: integer
        title: 
          type: string
        imdb:
          type: float
        metacritic:
          type: float
        tmdb:
          type: float
        rotten_tomatoes:
          type: float
        tv_com:
          type: float
        film_affinity:
          type: float
    Review:
      type: object
      properties:
        movie_name: 
          type: string
        recommend:
          type: float
        avg_score:
          type: float
