openapi: 3.0.0
info:
  title: Movie Review API
  description:
    This API provides historical review and movie data of the movies.
    Raw data provided by  The Internet Movie Database(IMDb) and The Movie Database(TMDB).
  version: 1.0.0
servers:
  - url: /movie-api/v1
paths:
  /movies:
    get:
      summary: Returns a list of movies.
      operationId: controller.get_movies
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MovieShort'
  /movie/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: string
    get:
      summary: Returns complete details of the specified movie by id
      operationId: controller.get_movie_details_id
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Movie'
  /movies/latest/:
    get:
      summary: Returns list of new movies order by release date
      operationId: controller.get_movies_latest
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieShort'
  /movies/cast/{cast_id}:
    parameters:
      - name: cast_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies that cast_id star in
      operationId: controller.get_movies_cast
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieShort'
  /movies/company/{company_id}:
    parameters:
      - name: company_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies that company_id contribute in
      operationId: controller.get_movies_company
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieShort'
  /movies/genre/{genre_id}:
    parameters:
      - name: genre_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Return a list of movies with genre_id
      operationId: controller.get_movies_genre
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MovieShort'
  /movie/rating/{imdb_id}:
    parameters:
      - name: imdb_id
        in: path
        required: true
        schema:
          type: integer
    get:
      summary: Returns movie's rating score from various of website
      operationId: controller.get_movie_rating
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
  /movies/AverageRating:
    get:
      summary: Returns average rating score from various of website for movies
      operationId: controller.get_movies_average_rating
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Rating'
  /movies/AverageReview:
    get:
      summary: Returns average review score from our primary data
      operationId: controller.get_movies_average_review
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Review'

components:
  schemas:
    MovieShort:
      type: object
      properties:
        id:
          type: integer
        imdb_id:
          type: string
        title:
          type: string
        release_date:
          type: string
        genre:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
    Movie:
      type: object
      properties:
        id:
          type: integer
        imdb_id:
          type: string
        title:
          type: string
        release_date:
          type: string
        cast:
          type: array
          items:
            $ref: '#/components/schemas/Person'
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
        production_company:
          type: array
          items:
            $ref: '#/components/schemas/ProductionCompany'
    Genre:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    ProductionCompany:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Person:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    Rating:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        imdb:
          type: number
        metacritic:
          type: number
        tmdb:
          type: number
        rotten_tomatoes:
          type: number
        tv_com:
          type: number
        film_affinity:
          type: number
    Review:
      type: object
      properties:
        movie_name:
          type: string
        recommend:
          type: number
        avg_score:
          type: number
