openapi: 3.0.0
info:
  title: Movie Review API
  description:
    This API provides historical review and movie data of the movies.
    Raw data provided by  The Internet Movie Database(IMDb) and The Movie Database(TMDB).
  version: 1.0.0
servers:
- url: /movie-api/v1
paths:
  /movies:
      get:
        summary: Returns a list of movies.
        operationId: controller.get_movies #temp controller
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/Movie'
  /movies/{movieId}:
      parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type : integer
      get:
        summary: Returns complete details of the specified movie by id
        operationId: controller.get_movie_details_id #temp controller
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'
  /movies/{movie_title}:
      parameters:
      - name: movie_title
        in: path
        required: true
        schema:
          type : string
      get:
        summary: Returns complete details of the specified movie by movie title
        operationId: controller.get_movie_details #temp controller
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'

components:
  schemas:
    Movie:
      type: object
      properties:
        title:
          type: string
        budget:
          type: number
        revenue:
          type: integer  
        release_date:
          type: string
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
        production_companies:
          type: array
          items:
            $ref: '#/components/schemas/ProductionCompany'
    Genre:
      type: object
      properties:
        name:
          type: string
    ProductionCompany:
      type: object
      properties:
        name:
          type: string
