openapi: 3.0.0
info:
  title: Movie Review API
  description:
    This API provides historical review and movie data of the movies.
    Raw data provided by  The Internet Movie Database(IMDb) and The Movie Database(TMDB).
  version: 1.0.0
servers:
- url: /movie-api/v1
paths:
  /movies:
      get:
        summary: Returns a list of movies.
        operationId: controller.get_movie
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  type: array
                  items:
                    $ref: '#/components/schemas/MovieShort'
  /movies/{movieId}:
      parameters:
      - name: movieId
        in: path
        required: true
        schema:
          type : integer
      get:
        summary: Returns complete details of the specified movie by id
        operationId: controller.get_movie_details_id
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/Movie'
  /movies/latest/:
      get:
        summary: Returns list of movies order by release date
        operationId: controller.get_movie_latest
        responses:
          200:
            description: Success
            content:
              application/json:
                schema:
                  $ref: '#/components/schemas/MovieShort'
  /movies/AverageRating:
        get:
          summary: Returns complete details of the specified movie by movie title
          operationId: controller.get_movie_average_rating
          responses:
            200:
              description: Success
              content:
                application/json:
                  schema:
                    $ref: '#/components/schemas/Movie'

components:
  schemas:
    MovieShort:
      type: object
      properties:
        id: 
          type: integer
        title: 
          type: string
        release_date:
          type: string
        genre:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
    Movie:
      type: object
      properties:
        title:
          type: string
        budget:
          type: number
        revenue:
          type: integer  
        release_date:
          type: string
        genres:
          type: array
          items:
            $ref: '#/components/schemas/Genre'
        production_companies:
          type: array
          items:
            $ref: '#/components/schemas/ProductionCompany'
    Genre:
      type: object
      properties:
        name:
          type: string
    ProductionCompany:
      type: object
      properties:
        name:
          type: string
